### PR TITLE
Translates in to es

### PR DESCRIPTION
**Pull request by ajmedina**
Im native spanish and translating your locales.

### CODE REVIEW

**Comment by renzuzu** [comment]
the locales are still incomplete

**Comment by ajmedina** [comment]
where? i translate 67 lines duplicate your en and translate into es

**Comment by renzuzu** [comment]
i mean most of the part of client lua does not even support translating.

**Comment by ajmedina** [comment]
aaaaa yeah ...i have translated the cliente and server files of various of
you scripts in my servers i upload that week and creating more locales
línes in the locales files not in the cliente and server script like
[new_translation_of_client]  that is?

**Pull request merged**
